let productsApi = [
  {
    id: 0,
    category: "adidas",
    title: "Cartoon Cotton T-Shirt",
    img: "../imgs/products/f1.jpg",
    quantity: 1,
    price: 158,
  },
  {
    id: 1,
    category: "nike",
    title: "GTA T-Shirt",
    img: "../imgs/products/f2.jpg",
    quantity: 1,
    price: 210,
  },
  {
    id: 2,
    category: "puma",
    title: "flower T-Shirt",
    img: "../imgs/products/f3.jpg",
    quantity: 1,
    price: 300,
  },
  {
    id: 3,
    category: "adidas",
    title: "white flower T-Shirt",
    img: "../imgs/products/f4.jpg",
    quantity: 1,
    price: 40,
  },
  {
    id: 4,
    category: "apipas",
    title: "blue T-Shirt",
    img: "../imgs/products/f5.jpg",
    quantity: 1,
    price: 130,
  },
  {
    id: 5,
    category: "zara",
    title: "two colors T-Shirt",
    img: "../imgs/products/f6.jpg",
    quantity: 1,
    price: 111,
  },
  {
    id: 6,
    category: "eltaw7ed",
    title: "eltaw7ed T-Shirt",
    img: "../imgs/products/f7.jpg",
    quantity: 1,
    price: 400,
  },
  {
    id: 7,
    category: "shein",
    title: "blue skirt",
    img: "../imgs/products/f8.jpg",
    quantity: 1,
    price: 60,
  },
  {
    id: 8,
    category: "adidas",
    title: "sky T-Shirt",
    img: "../imgs/products/n1.jpg",
    quantity: 1,
    price: 450,
  },
  {
    id: 9,
    category: "nike",
    title: "gray T-Shirt",
    img: "../imgs/products/n2.jpg",
    quantity: 1,
    price: 40,
  },
  {
    id: 10,
    category: "zara",
    title: "white T-Shirt",
    img: "../imgs/products/n3.jpg",
    quantity: 1,
    price: 90,
  },
  {
    id: 11,
    category: "adidas",
    title: "military T-Shirt",
    img: "../imgs/products/n4.jpg",
    quantity: 1,
    price: 170,
  },
];
